
services:
  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    container_name: reactivities-api
    ports:
      - "7000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=localhost,1433;Database=Reactivities;User Id=sa;Password=@7872238aA!;TrustServerCertificate=True;
